# Plugin napisany przez ic3dd_
# Placeholdery:
# [TRESC] - Zwraca tresc ogloszenia

announce:
  enabled: true

gui:
  name: "          Ogłoszenia"
  size: 9
  # W slotach czyli np. 9

items:
  1:
    name: " "
    lore:
      - " "
      - "&7dsc.gg/ic3dd-development"
    slot: 0
    material: BLACK_STAINED_GLASS_PANE
  2:
    name: " "
    lore:
      - " "
      - "&7dsc.gg/ic3dd-development"
    slot: 1
    material: BLACK_STAINED_GLASS_PANE
  3:
    name: "&7Informacje o serwerze"
    lore:
      - " "
      - "&7dsc.gg/ic3dd-development"
    slot: 2
    material: BOOK
  4:
    name: " "
    lore:
      - " "
      - "&7dsc.gg/ic3dd-development"
    slot: 3
    material: BLACK_STAINED_GLASS_PANE
  5:
    name: "        &cObecne ogłoszenie"
    lore:
      - " "
      - "&fTresc: &e[TRESC]"
      - " "
      - "&7dsc.gg/ic3dd-development"
    slot: 4
    material: BOOK
  6:
    name: " "
    lore:
      - " "
      - "&7dsc.gg/ic3dd-development"
    slot: 5
    material: BLACK_STAINED_GLASS_PANE
  7:
    name: "&cNajbliższy event"
    lore:
      - " "
      - "&7dsc.gg/ic3dd-development"
    slot: 6
    material: BOOK
  8:
    name: " "
    lore:
      - " "
      - "&7dsc.gg/ic3dd-development"
    slot: 7
    material: BLACK_STAINED_GLASS_PANE
  9:
    name: " "
    lore:
      - " "
      - "&7dsc.gg/ic3dd-development"
    slot: 8
    material: BLACK_STAINED_GLASS_PANE