name: Ic3ddOgloszenia
version: '1.0.0'
main: pl.ic3dd.ic3ddogloszenia.Main
api-version: '1.13'
author: ic3dd_
commands:
  ogloszenie:
    aliases: ['ogloszenia']
  ogloszeniareload:
    aliases: ['or']
  stworzogloszenie:
    aliases: ['sogloszenie']
